namespace WebActiveHealthyKidsVietNam;

public abstract class WebActiveHealthyKidsVietNamApplicationTestBase : WebActiveHealthyKidsVietNamTestBase<WebActiveHealthyKidsVietNamApplicationTestModule>
{

}
