using Volo.Abp;

namespace WebActiveHealthyKidsVietNam.EntityFrameworkCore;

public abstract class WebActiveHealthyKidsVietNamEntityFrameworkCoreTestBase : WebActiveHealthyKidsVietNamTestBase<WebActiveHealthyKidsVietNamEntityFrameworkCoreTestModule>
{

}
